# Generated by Django 4.1.2 on 2022-11-11 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0005_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="email",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rental.email",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
