# Generated by Django 4.1.2 on 2022-11-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0006_rental_email_alter_rental_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
